"use client";

import Link from "next/link";
import { 
  Mic2, 
  Play, 
  Pause, 
  Radio,
  ArrowRight,
  Clock,
  Database,
  Search,
  Sparkles,
  Zap,
  Globe,
  Waves
} from "lucide-react";
import { useState, useRef, useEffect } from "react";
import { UserButton, useAuth } from "@clerk/nextjs";
import { createClient } from "@supabase/supabase-js";

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || "";
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || "";

const supabase = (supabaseUrl && supabaseKey) 
  ? createClient(supabaseUrl, supabaseKey)
  : null;

const SUPABASE_BASE_URL = "https://jvdbazjbqmrkytnacjsa.supabase.co/storage/v1/object/public/GenBox%201";

interface SampleItem {
  title: string;
  description: string;
  file: string;
  type: string;
  duration: string;
  size: string;
}

interface SampleCategory {
  category: string;
  items: SampleItem[];
}

export default function BlogPage() {
  const { userId } = useAuth();
  const [playingFile, setPlayingFile] = useState<string | null>(null);
  const [samples, setSamples] = useState<SampleCategory[]>([]);
  const [loading, setLoading] = useState(true);
  const audioRefs = useRef<{ [key: string]: HTMLAudioElement | null }>({});

  useEffect(() => {
    async function fetchFiles() {
      try {
        setLoading(true);
        if (!supabase) {
          setSamples([]);
          return;
        }

        const { data: hindiFiles } = await supabase.storage.from("GenBox 1").list("hindi");
        const { data: englishFiles } = await supabase.storage.from("GenBox 1").list("english");

        const dynamicSamples = [
          {
            category: "PRO BROADCASTS",
            items: [
              { title: "DEBATE", description: "Multi-Speaker Cinematic Debate", file: "t30nMCjSuDQ", type: "video", duration: "00:45", size: "4K" },
              { title: "NARRATION", description: "Emotional Cinematic Voiceover", file: "Pwi8gsXqU2o", type: "video", duration: "00:52", size: "4K" }
            ]
          },
          {
            category: "HINDI ARCHIVE",
            items: (hindiFiles || []).filter(f => f.name !== ".emptyKeep" && f.name.includes('.wav')).map(f => {
              let title = f.name.split('-')[2] || f.name.replace('.wav', '');
              return {
                title: title.toUpperCase(),
                description: "High-fidelity production voice generated by GenBox Engine.",
                file: `${SUPABASE_BASE_URL}/hindi/${f.name}`,
                type: "audio",
                duration: "00:08",
                size: f.metadata ? `${(f.metadata.size / 1024).toFixed(0)} KB` : "250 KB"
              };
            })
          },
          {
            category: "ENGLISH ARCHIVE",
            items: (englishFiles || []).filter(f => f.name !== ".emptyKeep" && f.name.includes('.wav')).map(f => {
              let title = f.name.split('-')[2] || f.name.replace('.wav', '');
              if (title === "Ananya") title = "Priyanka";
              return {
                title: title.toUpperCase(),
                description: "International standard AI voice profile for global creators.",
                file: `${SUPABASE_BASE_URL}/english/${f.name}`,
                type: "audio",
                duration: "00:08",
                size: f.metadata ? `${(f.metadata.size / 1024).toFixed(0)} KB` : "250 KB"
              };
            })
          }
        ];

        setSamples(dynamicSamples);
      } catch (err) {
        console.error("Error fetching samples:", err);
      } finally {
        setLoading(false);
      }
    }

    fetchFiles();
  }, []);

  const togglePlay = (file: string) => {
    const audio = audioRefs.current[file];
    if (!audio) return;

    if (playingFile === file) {
      audio.pause();
      setPlayingFile(null);
    } else {
      if (playingFile && audioRefs.current[playingFile]) {
        audioRefs.current[playingFile]?.pause();
      }
      audio.play();
      setPlayingFile(file);
    }
  };

  return (
    <div className="min-h-screen bg-[#02040a] text-slate-200 selection:bg-indigo-500/30">
      {/* --- BACKGROUND LAYER (Simple) --- */}
      <div className="fixed inset-0 z-[-1]">
        <div className="absolute inset-0 bg-noise opacity-[0.02]" />
        <div className="absolute top-0 left-0 w-full h-full bg-[radial-gradient(circle_at_top_left,rgba(99,102,241,0.05)_0%,transparent_50%)]" />
      </div>

      {/* --- NAVIGATION --- */}
      <nav className="fixed top-0 inset-x-0 z-[100] border-b border-white/5 bg-[#02040a]/80 backdrop-blur-xl">
        <div className="max-w-7xl mx-auto px-6 h-20 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-3 group">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-indigo-500 to-violet-600 flex items-center justify-center">
              <Mic2 className="w-5 h-5 text-white" />
            </div>
            <span className="font-black text-white text-2xl tracking-tighter uppercase italic">GenBox</span>
          </Link>
          
          <div className="flex items-center gap-8">
            <Link href="/studio" className="hidden md:block text-[10px] font-black text-slate-400 hover:text-white transition-colors uppercase tracking-[0.3em]">Studio</Link>
            {userId ? (
              <div className="flex items-center gap-4">
                <Link
                  href="/studio"
                  className="px-6 py-2.5 rounded-xl bg-indigo-600 text-white text-xs font-black uppercase tracking-wider hover:bg-indigo-500 transition-all shadow-lg shadow-indigo-500/20"
                >
                  STUDIO
                </Link>
                <UserButton />
              </div>
            ) : (
              <Link
                href="/studio"
                className="px-6 py-2.5 rounded-xl bg-white text-black text-xs font-black uppercase tracking-wider hover:bg-slate-200 transition-all"
              >
                SIGN IN
              </Link>
            )}
          </div>
        </div>
      </nav>

      {/* --- HERO SECTION --- */}
      <header className="relative pt-48 md:pt-64 pb-20 px-6">
        <div className="max-w-7xl mx-auto text-center relative">
          
          {/* Floating Badges (SVG Characters like Home Page) */}
          <div className="absolute top-[-40px] left-[-20px] animate-float hidden xl:block">
            <div className="bg-white/5 backdrop-blur-md border border-white/10 rounded-2xl px-5 py-3 flex items-center gap-3">
              <div className="w-2.5 h-2.5 rounded-full bg-emerald-500 animate-pulse" />
              <span className="text-[10px] font-black text-emerald-400 uppercase tracking-widest">PRO READY</span>
            </div>
          </div>

          <div className="absolute bottom-[20px] right-[-40px] animate-float delay-1000 hidden xl:block">
            <div className="bg-white/5 backdrop-blur-md border border-white/10 rounded-2xl px-5 py-3 flex items-center gap-3">
              <Zap className="w-4 h-4 text-amber-400" />
              <span className="text-[10px] font-black text-amber-400 uppercase tracking-widest">NEURAL ENGINE</span>
            </div>
          </div>

          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 text-[10px] font-black uppercase tracking-[0.4em] mb-10">
            <Radio className="w-3 h-3" />
            Archive V1.0
          </div>

          {/* Fixed Text Clipping (pr-4 and leading-tight) */}
          <h1 className="text-6xl md:text-9xl font-black tracking-tight text-white leading-[1.1] mb-10 uppercase italic pr-4">
            VOICE <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 via-violet-400 to-pink-400">VAULT</span>
          </h1>

          <p className="max-w-3xl mx-auto text-lg md:text-xl text-slate-400 leading-relaxed mb-16 font-medium">
            Access our production-grade synthesis library. High-fidelity audio samples generated across multiple emotional profiles.
          </p>

          <div className="max-w-xl mx-auto flex items-center gap-4 p-2 rounded-2xl bg-white/5 border border-white/10">
            <div className="flex-1 flex items-center gap-3 px-4">
              <Search className="w-4 h-4 text-slate-500" />
              <input 
                type="text" 
                placeholder="SEARCH ARCHIVE..." 
                className="bg-transparent border-none outline-none text-[10px] font-black uppercase tracking-widest text-white placeholder:text-slate-600 w-full"
              />
            </div>
          </div>
        </div>
      </header>

      {/* --- ARCHIVE GRID --- */}
      <main className="py-20 px-6">
        <div className="max-w-7xl mx-auto">
          {loading ? (
            <div className="py-40 text-center">
              <div className="inline-block w-12 h-12 border-2 border-indigo-500/20 border-t-indigo-500 rounded-full animate-spin mb-4" />
              <p className="text-slate-500 font-black uppercase tracking-[0.4em] text-[10px]">SYNCING...</p>
            </div>
          ) : (
            <div className="space-y-40">
              {samples.map((category) => (
                <section key={category.category} className="space-y-12">
                  <div className="flex items-center gap-6">
                    <h2 className="text-2xl md:text-4xl font-black text-white tracking-tighter italic uppercase whitespace-nowrap">
                      {category.category}
                    </h2>
                    <div className="h-px flex-1 bg-white/10" />
                    <div className="flex items-center gap-2 text-[10px] font-black text-slate-500 uppercase tracking-widest">
                      <Globe className="w-3 h-3" />
                      GLOBAL REGION
                    </div>
                  </div>

                  <div className={`grid gap-8 ${category.category === "PRO BROADCASTS" ? "grid-cols-1 lg:grid-cols-2" : "grid-cols-1 md:grid-cols-2 lg:grid-cols-3"}`}>
                    {category.items.map((item) => (
                      <div
                        key={item.file}
                        className={`group relative rounded-3xl overflow-hidden transition-all duration-300 ${
                          item.type === "video" 
                            ? "bg-transparent" 
                            : "bg-white/[0.02] border border-white/5 p-8 hover:bg-white/[0.04]"
                        }`}
                      >
                        {item.type === "video" ? (
                          <div className="flex flex-col gap-6">
                            <div className="relative aspect-video rounded-3xl overflow-hidden border border-white/10 bg-black">
                              <iframe 
                                className="w-full h-full"
                                src={`https://www.youtube.com/embed/${item.file}?modestbranding=1&rel=0`}
                                title={item.title}
                                allowFullScreen
                              ></iframe>
                            </div>
                            <div>
                              <h3 className="text-4xl font-black text-white italic uppercase tracking-tighter mb-2">{item.title}</h3>
                              <p className="text-slate-500 font-bold uppercase tracking-[0.3em] text-[10px]">{item.description}</p>
                            </div>
                          </div>
                        ) : (
                          <div className="flex flex-col">
                            {/* Card Header */}
                            <div className="flex items-start justify-between mb-8">
                              <div className="space-y-3">
                                <div className="flex items-center gap-2">
                                  <Sparkles className="w-3 h-3 text-indigo-400" />
                                  <span className="text-[8px] font-black text-indigo-400 uppercase tracking-widest">NEURAL SAMPLE</span>
                                </div>
                                <h3 className="text-2xl font-black text-white tracking-tight leading-tight">{item.title}</h3>
                                <div className="flex items-center gap-4 text-[9px] font-bold text-slate-600 uppercase tracking-widest">
                                  <span className="flex items-center gap-1.5"><Clock className="w-3 h-3" /> {item.duration}</span>
                                  <span className="flex items-center gap-1.5"><Database className="w-3 h-3" /> {item.size}</span>
                                </div>
                              </div>
                              <button 
                                onClick={() => togglePlay(item.file)}
                                className={`w-14 h-14 rounded-2xl flex items-center justify-center transition-all ${
                                  playingFile === item.file 
                                    ? 'bg-indigo-600 text-white' 
                                    : 'bg-white/5 text-white hover:bg-white/10'
                                }`}
                              >
                                {playingFile === item.file 
                                  ? <Pause className="w-6 h-6 fill-current" /> 
                                  : <Play className="w-6 h-6 fill-current ml-1" />
                                }
                              </button>
                            </div>

                            <p className="text-slate-500 text-xs leading-relaxed mb-8 italic">
                              "{item.description}"
                            </p>

                            {/* Extra Details */}
                            <div className="pt-6 border-t border-white/5 grid grid-cols-2 gap-4">
                              <div className="space-y-1">
                                <p className="text-[8px] font-black text-slate-600 uppercase tracking-widest">Sample Rate</p>
                                <p className="text-[10px] font-bold text-slate-400">48kHz / 24-bit</p>
                              </div>
                              <div className="space-y-1">
                                <p className="text-[8px] font-black text-slate-600 uppercase tracking-widest">Engine ID</p>
                                <p className="text-[10px] font-bold text-slate-400">GBX-PRO-01</p>
                              </div>
                            </div>
                          </div>
                        )}

                        {item.type === "audio" && (
                          <audio 
                            ref={(el) => { audioRefs.current[item.file] = el; }}
                            onEnded={() => setPlayingFile(null)}
                            className="hidden"
                          >
                            <source src={item.file} type="audio/wav" />
                          </audio>
                        )}
                      </div>
                    ))}
                  </div>
                </section>
              ))}
            </div>
          )}
        </div>
      </main>

      {/* --- CTA SECTION --- */}
      <section className="py-32 px-6">
        <div className="max-w-4xl mx-auto">
          <div className="relative p-12 md:p-20 rounded-[3rem] bg-indigo-600 overflow-hidden text-center">
            <div className="absolute top-0 left-0 w-64 h-64 bg-white/10 rounded-full blur-[80px] -translate-x-1/2 -translate-y-1/2" />
            <h2 className="relative z-10 text-4xl md:text-6xl font-black text-white tracking-tighter mb-10 leading-tight uppercase italic">
              START YOUR <br /> PRODUCTION
            </h2>
            <Link 
              href="/studio" 
              className="relative z-10 inline-flex items-center gap-4 px-10 py-5 bg-white text-black font-black text-lg rounded-2xl hover:bg-slate-100 transition-all"
            >
              OPEN STUDIO
              <ArrowRight className="w-6 h-6" />
            </Link>
          </div>
        </div>
      </section>

      {/* --- FOOTER --- */}
      <footer className="py-20 px-6 border-t border-white/5">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center justify-between gap-10">
          <div className="flex items-center gap-3">
            <Mic2 className="w-6 h-6 text-indigo-500" />
            <span className="font-black text-white text-xl tracking-tighter uppercase italic">GenBox</span>
          </div>
          <p className="text-slate-600 text-[10px] font-black uppercase tracking-[0.3em]">© 2026 NEURAL MEDIA LABS</p>
        </div>
      </footer>
    </div>
  );
}
